name: FreeBSD (with Clang)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        uses: vmactions/freebsd-vm@v1
        with:
          prepare: pkg install -y cmake openssl gcc13
          copyback: false
          run: |
            pwd
            ls -lah
            echo "---------------"
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make neblina
            make neblina-tests
            ./neblina-tests
      - name: Load test
        continue-on-error: true
        run: |
          mkdir build-release
          cd build-release
          cmake ..
          make -j8 neblina-load-test
          ./neblina-load-test -t -a 2000 -n 8 -r
          ./neblina-load-test -s -a 100 -n 8 -r
