name: Linux (with GCC)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc15

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          add-apt-repository ppa:ubuntu-toolchain-r/test
          apt-get update
          apt-get install -y libssl-dev valgrind
          apt-get install --only-upgrade -y libstdc++6
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
      - name: Configure CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build executable
        working-directory: ./build
        run: make neblina
      - name: Build and run tests
        working-directory: ./build
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
          make -j8 neblina-tests
          ./neblina-tests
      - name: Check for leaks
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-leaks
      - name: Check threads (drd)
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-drd
      - name: Check threads (helgrind)
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-helgrind
      - name: Load test
        continue-on-error: true
        run: |
          mkdir build-release
          cd build-release
          cmake ..
          make -j8 neblina-load-test
          ./neblina-load-test -t -a 2000 -n 8 -r
          ./neblina-load-test -s -a 100 -n 8 -r
