name: Linux (with GCC)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc16

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
          add-apt-repository ppa:ubuntu-toolchain-r/test
          apt-get update
          apt-get install -y libssl-dev valgrind libstdc++6
      - name: Configure CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build executable
        working-directory: ./build
        run: make neblina
      - name: Build and run tests
        working-directory: ./build
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
          make neblina-tests
          ./neblina-tests
      #- name: Load test
      #  working-directory: ./build
      #  run: make neblina-load-test && ./neblina-load-test
      - name: Check for leaks
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-leaks
      - name: Check threads (drd)
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-drd
      - name: Check threads (helgrind)
        continue-on-error: true
        working-directory: ./build
        run: make neblina-tests-helgrind
