name: MacOS (with Clang)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4
      - name: Install make
        run: brew install make openssl
      - name: Configure CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug  ..
      - name: Build executable
        working-directory: ./build
        run: make neblina neblina-tests
      - name: Run tests
        working-directory: ./build
        run: ./neblina-tests
      - name: Load test
        continue-on-error: true
        run: |
          mkdir build-release
          cd build-release
          cmake ..
          make -j8 neblina-load-test
          ./neblina-load-test -t -a 2000 -n 8 -r
          ./neblina-load-test -s -a 100 -n 8 -r
