name: Windows (with MSVC)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md
      - name: Run tests
        run: mkdir build && cd build && cmake .. && msbuild neblina.sln /t:neblina,neblina-tests && cd Debug && dir && .\neblina-tests.exe
      - name: Load test
        continue-on-error: true
        run: |
          mkdir build-release
          cd build-release
          cmake ..
          msbuild neblina.sln /t:neblina-load-test
          cd Debug
          .\neblina-load-test.exe -t -a 2000 -n 8 -r
          .\neblina-load-test.exe -s -a 100 -n 8 -r
